### ISSUE TITLE
model

### ISSUE THREAD

**Issue by VB10** [kyskerem/social_app#1]
https://github.com/kyskerem/social_app/blob/c2a447913f757cde0d4a7f9106af3be26c1f7ef1/lib/features/post/comment/comment_provider.dart#L21

model gonder bunu tek tek json yapma
sana gelen modele copy with ile yeni oluştur muhaukakk
readme projey egerekiyor

**Comment by kyskerem** [comment]
teşekkür ederim ama projeye devam etmiyicem ileriki projelerim için dikkat edicem
